import os
from dotenv import load_dotenv

load_dotenv()  # loads variables from .env

#FRED API KEY
fred_api_key = os.getenv("FRED_API_KEY")

# project configuration
RESULTS_DIR = "../results"

# data sources configuration
UNRATE_DATASET= 'UNRATE'
SPY_DATASET = 'SPY'
NVIDIA_DATASET = 'NVDA'
START_DATE = '2000-01-01'
END_DATE = '2025-09-01'
AI_BOOM_START_DATE = '2015-12-01'
UNRATE_DATASET_COLOR = '#555555'
SPY_DATASET_COLOR = 'blue'
NVIDIA_DATASET_COLOR = '#76B900'
UNRATE_DATASET_PRIMARY_COLUMN_NAME = 'Unemployment Rate'
COVID_RAW = True
COVID_SMOOTHED = False
UNRATE_COVID_PLOT_BASE_TITLE = 'Unemployment Rate With Covid'
UNRATE_PLOT_BASE_TITLE = 'Unemployment Rate'
STOCK_SAMPLING_FREQUENCY = '1mo'
SPY_DATASET_STOCK_NAME = 'SPY'
USE_RAW_STOCK_DATA = False
USE_LOG_CLOSE_STOCK_PRICE = True
SPY_LOG_PLOT_BASE_TITLE = 'SPY Log Close Price'
SPY_PLOT_BASE_TITLE = 'SPY Close Price'
NVIDIA_DATASET_STOCK_NAME = 'NVIDIA'
NVIDIA_LOG_PLOT_BASE_TITLE = 'NVIDIA Log Close Price'
NVIDIA_PLOT_BASE_TITLE = 'NVIDIA Close Price'
PRE_AI_BOOM = 'Pre'
POST_AI_BOOM = 'Post'